### ISSUE TITLE
Cammie

### ISSUE THREAD

**Issue by Topvennie** [ZeusWPI/SCC#2]
### Tasks

- [x] Optimize `Cammie Update`
- [x] Check compatibility with colors
- [x] Improve esthetics
- [x] Documentation
- [x] Potentially use `List` instead of `TextView`
- [x] Line count with word wrap (`Scrollbar`)
